apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-monitoring
  labels:
    app: grafana
    component: core
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: grafana-port
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
    component: core
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: kube-monitoring
spec:
  rules:
  - host: grafana.k8smikhael.com
    http:
      paths:
        - backend:
            serviceName: grafana
            servicePort: 80
