apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: kube-monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: prometheus-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: kube-monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: prometheus.k8smikhael.com
    http:
      paths:
        - backend:
            serviceName: prometheus-service
            servicePort: 80
